Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np

arr= np.array([1,2,5.1,9.2,8])
#add 2 to all elements
for i in range(len(arr)):
    arr[i]+=2
print(arr)
#multiply 3 with all elements
for i in range(len(arr)):
    arr[i]*=3
print(arr)
#divide every element by 2
for i in range(len(arr)):
    arr[i]/=2
print(arr)

[ 3.   4.   7.1 11.2 10. ]
[ 9.  12.  21.3 33.6 30. ]
[ 4.5   6.   10.65 16.8  15.  ]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np
#reversing array
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

#finding most frequent value
def most_frequent_values(arr):
    unique_values, counts = np.unique(arr, return_counts=True)  #used to find unique values in array
    max_count = np.max(counts)
    most_frequent = unique_values[counts == max_count]

    result = {}
    for value in most_frequent:
        indices = np.where(arr == value)[0]  #used to find indices
        result[value] = indices.tolist()

    return result

x = np.array([1,2,3,4,5,1,2,1,1,1])
y= np.array([1,1,1,2,3,4,2,4,3,3])

result_x= most_frequent_values(x)
result_y= most_frequent_values(y)

print(result_x)
print(result_y)

[5 4 6 3 2 1]
{1: [0, 5, 7, 8, 9]}
{1: [0, 1, 2], 3: [4, 8, 9]}


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named (Your_Name) with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np

Harshit = np.array(np.linspace(10,100,25))
print(Harshit)
print(Harshit.ndim)
print(Harshit.shape)
print(Harshit.size)
print(Harshit.dtype)
print(Harshit.nbytes)

Harshit2 = Harshit.copy()

transpose = Harshit.reshape(25,1)
print(transpose)

transpose2 = Harshit2.T
print(transpose2)

print("\nDoes .T work the same way?", np.array_equal(transpose, transpose2))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Does .T work the same way? False


Q5. Create a 2-D Array of three rows and four columns, named ucs420_(your_name)
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_(your_name). Resize the array to two rows and three
columns and name it as resized_ ucs420_(your_name).

In [ ]:
import numpy as np

ucs420_Harshit = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Harshit)
mean = np.mean(ucs420_Harshit)
print(mean)

median = np.median(ucs420_Harshit)
print(median)

max = np.max(ucs420_Harshit)
print(max)

min = np.min(ucs420_Harshit)
print(min)

unique = np.unique(ucs420_Harshit)
print(unique)

reshaped_ucs420_Harshit = ucs420_Harshit.reshape(4,3)
print(reshaped_ucs420_Harshit)

resized_ucs420_Harshit = np.resize(ucs420_Harshit, (2, 3))
print("Resized Array (2x3):")
print(resized_ucs420_Harshit)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
[[10 20 30]
 [40 50 60]]
